version: "3"
networks:
  kalinet:
    ipam:
      config:
        - subnet: 172.31.0.0/24

services:

  kali:
    build: kali/
    image: forgottenbeast/kali_docker
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - SSH_PW=
      - SSH_USER=
    networks:
      kalinet:
        ipv4_address: 172.31.0.2

    deploy:
      placement:
        constraints:
          - node.role == manager
    #open ports for reverse meterpreter shells and that kind of things
    ports:
      - "400-500:400-500/tcp"

  gateway:
    image: forgottenbeast/vpnd_x86
    cap_add:
      - NET_ADMIN

    volumes:
      - "./vpn.conf:/etc/openvpn/vpn.conf"

    devices:
      - "/dev/net/tun:/dev/net/tun"

    deploy:
      placement:
        constraints:
          - node.role == worker

    networks:
      kalinet:
        ipv4_address: 172.31.0.254

  torhh:
    restart: always
    image: goldy/tor-hidden-service
    networks:
      - kalinet

    deploy:
      placement:
        constraints:
          - node.role == manager
    links:
      - kali
    environment:
      KALI_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICWwIBAAKBgQCZqWFqN7MeHCb3xuXZcwY68i3SoS7WFczkZsJil/j8F3ck9VQt
        xHz4NKuGuXRV0QoO9v8ZGgIul1UTk+sO1M3tb4X3atrRm9X/J7vQjVj0qNiCxlW/
        8gzoENlfgPXRakA693lk+NNPGpunqxR7N5cA+p8Q9FB2h4QPtP+I3qn7OwIDAQAB
        AoGAQHH3dzLRHom0FisG70H8lPBJI5OSLxuJiSlH0U3nkOLOh2OU4HUN7JM6dRCG
        qA855rjUmFR+Icg6WDGrXdcGXi4Jiw4tZ4yckkB4kwGaZZT9xfbhLxNujxWxOxZE
        XiZXkPHEguDq9+9gg7a8ZEyePQ6QGqDzqio9vwAuHKL8YSECQQDJ2GxM+z9goucY
        UjKiYxRT3b1logItz5CCkF9EJmfRqXuoK0BFnpRk+n5qJLqSGh+CwM13AAljpKd1
        PD9yGXdTAkEAwuN/YkUTbr3AEnDxQZ81mLJ31+PNEqDT2xpLSwc3kvwNGukjXTjb
        UsSxTGkCTK9KTBncbnJRepqai2F75RN3eQJAL5inQSfl9AW19Ng9NGmku3oIVVT0
        qpTNgNxGeq2Lwbbzf95jE4eneoBPGvx6OkWKtKx+RtdtX1/OVSjV1TQIHQJAPShT
        Ey2GGZxmJ+NVcjhaA18OCKut8QiTMxCfTB4prHB4VFeRB3IOMX0T/lx9oj7n29XJ
        vMcXFphpow+mZ46iUQJAezFLSB9OOCos+bAyaZBNvT6cMihhamekBQ0ZllEFUZ0t
        iEnaRiIgQQ/6hiEz/+lbK8iUOaToz0G91/CmFDa2gg==
        -----END RSA PRIVATE KEY-----

      KALI_PORTS: "22:22"
