- name: "Install: ansible docker requirements and openssl"
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: True
  with_items:
    - python-setuptools
    - openssl

- name: "Install: python pip"
  easy_install:
    name: pip
    state: latest

- name: "Install: docker-py"
  pip:
    name: "{{ item }}"
  with_items:
    - docker-py

- name: "Install: docker-compose"
  pip:
    name: docker-compose
    version: 1.9.0

- name: "Check if docker is installed"
  command: which docker
  register: docker
  ignore_errors: True

- name: "Docker install"
  include: docker_install.yml
  become: True
  when: docker|failed
